# Generated by Django 3.2.5 on 2021-07-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(default=None, max_length=10)),
                ('contact', models.CharField(default=None, max_length=20)),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(default=None, max_length=20)),
                ('mapped', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=9)),
                ('description', models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
