# Generated by Django 3.2.5 on 2021-07-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostOBD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_model', models.CharField(choices=[('tag model 001', 'Tag Model 001'), ('tag model 002', 'Tag Model 002')], default='tag model 001', max_length=20)),
                ('tag_Name', models.CharField(default=None, max_length=10)),
                ('tag_mapped', models.CharField(choices=[('assigned', 'Assigned'), ('not assigned', 'Not Assigned')], default='assigned', max_length=20)),
                ('car_asset', models.CharField(choices=[('i20,hyundai', 'i20,Hyundai'), ('swift,maruthi', 'Swift,Maruthi')], default='i20,hyundai', max_length=20)),
                ('site', models.CharField(default=None, max_length=20)),
                ('location', models.CharField(default=None, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=9)),
                ('description', models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
