# Generated by Django 3.2.5 on 2021-07-20 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_postobd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postobd',
            old_name='tag_Name',
            new_name='tag_name',
        ),
    ]
