# Generated by Django 3.2.5 on 2021-07-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_tag_name_postobd_tag_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(default=None, max_length=20)),
                ('car_brand', models.CharField(default=None, max_length=10)),
                ('site', models.CharField(default=None, max_length=20)),
                ('location', models.CharField(default=None, max_length=20)),
                ('tag_mapped', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=20)),
                ('tag_model', models.CharField(choices=[('tag model 001', 'Tag Model 001'), ('tag model 002', 'Tag Model 002')], default='tag model 001', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=9)),
                ('demo_model', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=9)),
                ('alerts_time', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='online', max_length=9)),
                ('description', models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
